export const metadata = {
  title: 'contact',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <h1>layout.jsx me aapka swagat hai</h1>{children}</body>
    </html>
  )
}
